In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('cars.csv')

In [3]:
df.shape

(8128, 5)

In [4]:
df.sample(10)

          brand  km_driven    fuel         owner  selling_price
2095  Chevrolet     120000  Diesel  Second Owner         225000
1657    Hyundai      29000  Petrol   First Owner         650000
7467    Hyundai     100000  Petrol  Second Owner         250000
4111     Maruti      25000  Petrol   First Owner         235000
1913   Mahindra     100000  Diesel   First Owner         450000
99      Hyundai     110000  Diesel   First Owner         725000
6602     Maruti      82000  Diesel   First Owner         825000
7229     Maruti      90000  Petrol  Second Owner         220000
6198     Datsun      20000  Petrol   First Owner         275000
5792     Maruti      80000     CNG   First Owner         320000

In [5]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [7]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['selling_price']),df['selling_price'],test_size=0.3,random_state=42)

In [9]:
x_train

         brand  km_driven    fuel         owner
6783    Maruti     120000  Petrol   Third Owner
1073    Toyota     100000  Diesel   First Owner
7756       BMW      39000  Diesel   First Owner
144     Toyota      39000  Petrol   First Owner
6424    Maruti      70000  Diesel  Second Owner
...        ...        ...     ...           ...
5226  Mahindra     120000  Diesel   First Owner
5390    Maruti      80000  Diesel  Second Owner
860    Hyundai      35000  Petrol   First Owner
7603    Maruti      27000  Diesel   First Owner
7270    Maruti      70000  Petrol  Second Owner

[5689 rows x 4 columns]

In [10]:
# ab hamne jaise ki dekha tha ki fuel or owner me to resonable categories hai lekin brand me bahut saari

In [11]:
cols=['owner','fuel']

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe=OneHotEncoder(sparse_output=False,drop='first',dtype='int')

In [14]:
encoder_x_train=pd.DataFrame(ohe.fit_transform(x_train[cols]),columns=ohe.get_feature_names_out(cols), index=x_train.index)

In [15]:
encoder_x_train

,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
6783,0,0,0,1,0,0,1
1073,0,0,0,0,1,0,0
7756,0,0,0,0,1,0,0
144,0,0,0,0,0,0,1
6424,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...
5226,0,0,0,0,1,0,0
5390,0,1,0,0,1,0,0
860,0,0,0,0,0,0,1
7603,0,0,0,0,1,0,0
7270,0,1,0,0,0,0,1

In [16]:
x_train=x_train.drop(columns=['fuel','owner'])

In [17]:
x_train

         brand  km_driven
6783    Maruti     120000
1073    Toyota     100000
7756       BMW      39000
144     Toyota      39000
6424    Maruti      70000
...        ...        ...
5226  Mahindra     120000
5390    Maruti      80000
860    Hyundai      35000
7603    Maruti      27000
7270    Maruti      70000

[5689 rows x 2 columns]

In [18]:
x_train=pd.concat([x_train,encoder_x_train],axis=1)

In [19]:
x_train

,brand,km_driven,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
6783,Maruti,120000,0,0,0,1,0,0,1
1073,Toyota,100000,0,0,0,0,1,0,0
7756,BMW,39000,0,0,0,0,1,0,0
144,Toyota,39000,0,0,0,0,0,0,1
6424,Maruti,70000,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
5226,Mahindra,120000,0,0,0,0,1,0,0
5390,Maruti,80000,0,1,0,0,1,0,0
860,Hyundai,35000,0,0,0,0,0,0,1
7603,Maruti,27000,0,0,0,0,1,0,0
7270,Maruti,70000,0,1,0,0,0,0,1

### ab problem dekh

In [20]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

# itni catwgories nahi banayi jaa sakti

is liye in type ke prblems me ham eakthreshhold lenge

In [21]:
threshold = 120
count=df.groupby(by='brand').count()['fuel']
count
count=count[count>threshold]
count

brand
Chevrolet      230
Ford           397
Honda          467
Hyundai       1415
Mahindra       772
Maruti        2448
Renault        228
Tata           734
Toyota         488
Volkswagen     186
Name: fuel, dtype: int64

In [22]:
df['brand']=np.where(
    df['brand'].isin(count),
    df['brand'],
    'others'
)

In [23]:
df

       brand  km_driven    fuel                 owner  selling_price
0     others     145500  Diesel           First Owner         450000
1     others     120000  Diesel          Second Owner         370000
2     others     140000  Petrol           Third Owner         158000
3     others     127000  Diesel           First Owner         225000
4     others     120000  Petrol           First Owner         130000
...      ...        ...     ...                   ...            ...
8123  others     110000  Petrol           First Owner         320000
8124  others     119000  Diesel  Fourth & Above Owner         135000
8125  others     120000  Diesel           First Owner         382000
8126  others      25000  Diesel           First Owner         290000
8127  others      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]