In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('cars.csv')

In [3]:
df.shape

(8128, 5)

In [4]:
df.sample(10)

         brand  km_driven    fuel         owner  selling_price
2715    Maruti      10300  Petrol   First Owner         185000
2103  Mahindra     120000  Diesel   Third Owner         300000
6936      Tata     110000  Diesel   Third Owner          80000
4894  Mahindra      88754  Diesel   First Owner        1100000
1438    Maruti      54723  Diesel   First Owner         470000
7655  Mahindra      60000  Diesel   First Owner        1000000
574    Hyundai      75000  Diesel   First Owner         525000
3064    Maruti      62900  Petrol   First Owner         135000
3397    Toyota     100000  Diesel  Second Owner         280000
2729  Mahindra      50000  Diesel   First Owner         660000

In [5]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [7]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['selling_price']),df['selling_price'],test_size=0.3,random_state=42)

In [9]:
x_train

         brand  km_driven    fuel         owner
6783    Maruti     120000  Petrol   Third Owner
1073    Toyota     100000  Diesel   First Owner
7756       BMW      39000  Diesel   First Owner
144     Toyota      39000  Petrol   First Owner
6424    Maruti      70000  Diesel  Second Owner
...        ...        ...     ...           ...
5226  Mahindra     120000  Diesel   First Owner
5390    Maruti      80000  Diesel  Second Owner
860    Hyundai      35000  Petrol   First Owner
7603    Maruti      27000  Diesel   First Owner
7270    Maruti      70000  Petrol  Second Owner

[5689 rows x 4 columns]

In [10]:
# ab hamne jaise ki dekha tha ki fuel or owner me to resonable categories hai lekin brand me bahut saari

In [11]:
cols=['owner','fuel']

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe=OneHotEncoder(sparse_output=False,drop='first',dtype='int')

In [14]:
encoder_x_train=pd.DataFrame(ohe.fit_transform(x_train[cols]),columns=ohe.get_feature_names_out(cols), index=x_train.index)

In [15]:
encoder_x_train

,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
6783,0,0,0,1,0,0,1
1073,0,0,0,0,1,0,0
7756,0,0,0,0,1,0,0
144,0,0,0,0,0,0,1
6424,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...
5226,0,0,0,0,1,0,0
5390,0,1,0,0,1,0,0
860,0,0,0,0,0,0,1
7603,0,0,0,0,1,0,0
7270,0,1,0,0,0,0,1

In [16]:
x_train=x_train.drop(columns=['fuel','owner'])

In [17]:
x_train

         brand  km_driven
6783    Maruti     120000
1073    Toyota     100000
7756       BMW      39000
144     Toyota      39000
6424    Maruti      70000
...        ...        ...
5226  Mahindra     120000
5390    Maruti      80000
860    Hyundai      35000
7603    Maruti      27000
7270    Maruti      70000

[5689 rows x 2 columns]

In [18]:
x_train=pd.concat([x_train,encoder_x_train],axis=1)

In [19]:
x_train

,brand,km_driven,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
6783,Maruti,120000,0,0,0,1,0,0,1
1073,Toyota,100000,0,0,0,0,1,0,0
7756,BMW,39000,0,0,0,0,1,0,0
144,Toyota,39000,0,0,0,0,0,0,1
6424,Maruti,70000,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
5226,Mahindra,120000,0,0,0,0,1,0,0
5390,Maruti,80000,0,1,0,0,1,0,0
860,Hyundai,35000,0,0,0,0,0,0,1
7603,Maruti,27000,0,0,0,0,1,0,0
7270,Maruti,70000,0,1,0,0,0,0,1

### ab problem dekh

In [20]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

# itni catwgories nahi banayi jaa sakti

is liye in type ke prblems me ham eakthreshhold lenge

In [21]:
threshold = 120
count=df.groupby(by='brand').count()['fuel']
count
count=count[count>threshold].index
count

Index(['Chevrolet', 'Ford', 'Honda', 'Hyundai', 'Mahindra', 'Maruti',
       'Renault', 'Tata', 'Toyota', 'Volkswagen'],
      dtype='object', name='brand')

In [22]:
df['brand']=np.where(
    df['brand'].isin(count),
    df['brand'],
    'others'
)

In [23]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1      others     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [24]:
threshold = 120
count=x_train.groupby(by='brand').count()['km_driven']
count
count=count[count>threshold].index
count

Index(['Chevrolet', 'Ford', 'Honda', 'Hyundai', 'Mahindra', 'Maruti',
       'Renault', 'Tata', 'Toyota', 'Volkswagen'],
      dtype='object', name='brand')

In [25]:
x_train['brand']=np.where(
    x_train['brand'].isin(count),
    x_train['brand'],
    'others'
)

In [26]:
x_train

,brand,km_driven,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
6783,Maruti,120000,0,0,0,1,0,0,1
1073,Toyota,100000,0,0,0,0,1,0,0
7756,others,39000,0,0,0,0,1,0,0
144,Toyota,39000,0,0,0,0,0,0,1
6424,Maruti,70000,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
5226,Mahindra,120000,0,0,0,0,1,0,0
5390,Maruti,80000,0,1,0,0,1,0,0
860,Hyundai,35000,0,0,0,0,0,0,1
7603,Maruti,27000,0,0,0,0,1,0,0
7270,Maruti,70000,0,1,0,0,0,0,1

In [27]:
encoder_x_test=pd.DataFrame(ohe.transform(x_test[cols]),columns=ohe.get_feature_names_out(cols), index=x_test.index)

In [28]:
encoder_x_test

,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
1971,0,0,0,1,0,0,1
4664,0,0,0,0,1,0,0
5448,0,0,0,0,1,0,0
3333,0,1,0,0,0,0,1
2316,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...
462,0,0,0,0,0,0,1
1956,0,0,0,1,1,0,0
3782,0,0,0,0,0,0,1
799,0,0,0,0,0,0,1
2402,0,0,0,1,1,0,0

In [29]:
x_test.drop(columns=['fuel','owner'])

        brand  km_driven
1971    Honda     110000
4664     Tata     291977
5448   Maruti      70000
3333    Honda     120000
2316   Maruti      69000
...       ...        ...
462   Hyundai      35000
1956   Toyota      90000
3782   Maruti      20000
799   Renault      60000
2402   Toyota     270000

[2439 rows x 2 columns]

In [30]:
x_test=pd.concat([x_test,encoder_x_test],axis=1)

In [50]:
x_test

,brand,km_driven,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Renault,brand_Tata,brand_Toyota,brand_Volkswagen,brand_others
1971,Honda,110000.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4664,Tata,291977.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5448,Maruti,70000.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3333,Honda,120000.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316,Maruti,69000.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [32]:
x_test['brand']=np.where(
    x_test['brand'].isin(count),
    x_test['brand'],
    'others'
)

In [33]:
cols=['brand']
encoded_x_train=pd.DataFrame(ohe.fit_transform(x_train[cols]),columns=ohe.get_feature_names_out(cols), index=x_train.index)

In [34]:
# encoded_x_train

,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Renault,brand_Tata,brand_Toyota,brand_Volkswagen,brand_others
6783,0,0,0,0,1,0,0,0,0,0
1073,0,0,0,0,0,0,0,1,0,0
7756,0,0,0,0,0,0,0,0,0,1
144,0,0,0,0,0,0,0,1,0,0
6424,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
5226,0,0,0,1,0,0,0,0,0,0
5390,0,0,0,0,1,0,0,0,0,0
860,0,0,1,0,0,0,0,0,0,0
7603,0,0,0,0,1,0,0,0,0,0
7270,0,0,0,0,1,0,0,0,0,0

In [35]:
x_train=x_train.drop(columns=['brand'])
x_train=pd.concat([x_train,encoded_x_train],axis=1)

In [49]:
x_train
# x_test

,km_driven,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Renault,brand_Tata,brand_Toyota,brand_Volkswagen,brand_others
6783,0.050837,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1073,0.042364,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7756,0.016522,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
144,0.016522,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6424,0.029655,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,0.050837,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5390,0.033891,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
860,0.014827,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7603,0.011438,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
7270,0.029655,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [37]:
cols=['brand']
encoded_x_test=pd.DataFrame(ohe.transform(x_test[cols]),columns=ohe.get_feature_names_out(cols), index=x_test.index)

In [38]:
# x_test=x_test.drop(columns=['brand'])
# x_test=pd.concat([x_test,encoded_x_test],axis=1)
x_test=x_test.drop(columns=['fuel','owner'])

In [39]:
x_test=pd.concat([x_test,encoded_x_test])
x_test

,brand,km_driven,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Renault,brand_Tata,brand_Toyota,brand_Volkswagen,brand_others
1971,Honda,110000.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4664,Tata,291977.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5448,Maruti,70000.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3333,Honda,120000.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316,Maruti,69000.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [40]:
from sklearn.preprocessing import MinMaxScaler

In [41]:
scalar=MinMaxScaler()

In [42]:
x_train = pd.DataFrame(scalar.fit_transform(x_train), columns=x_train.columns, index=x_train.index)

In [43]:
x_train

,km_driven,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Renault,brand_Tata,brand_Toyota,brand_Volkswagen,brand_others
6783,0.050837,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1073,0.042364,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7756,0.016522,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
144,0.016522,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6424,0.029655,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,0.050837,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5390,0.033891,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
860,0.014827,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7603,0.011438,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
7270,0.029655,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [44]:
# x_test = pd.DataFrame(scalar.transform(x_test), columns=x_test.columns, index=x_test.index)
x_test

,brand,km_driven,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Renault,brand_Tata,brand_Toyota,brand_Volkswagen,brand_others
1971,Honda,110000.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4664,Tata,291977.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5448,Maruti,70000.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3333,Honda,120000.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316,Maruti,69000.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [45]:
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [46]:
model=LinearRegression()

In [47]:
model.fit(x_train,y_train)

LinearRegression()

In [48]:
pred=model.predict(x_test)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- brand

In [ ]:
result=r2_score(y_test,pred)
result